---
# m1 flavor used for vGPU NVIDIA RTX 6000 (Turing) with 12GB GPU-memory
# for osl region
public: false
properties:
  hw_rng:allowed: 'True'
  hw_rng:rate_bytes: 1000000
  hw_rng:rate_period: 60
  resources:VGPU: '1'
  trait:CUSTOM_NREC_VGPU_RTX6000_TURING_12G: 'required'
g1.rtx6k_turing.12g:
  'g1.rtx6k_turing.12g':
    vcpus: 8
    ram: 61440 # 60 GiB
    disk: 60
