---
desc: 'Manage Sensu'
actions:
  events:        'list events'
  delete:        'Delete host from Sensu'
  silence:       'Silence host'
  unsilence:     'Unsilence host'
  list-silenced: 'Lists silenced hosts'
  show-silenced: 'Show silenced host'
  silence-known: 'Silence known issues'
opt_args:
  '-H':
    'sub':      ['delete','silence','unsilence', 'show-silenced']
    'dest':     'host'
    'help':     'Hostname'
    'required': True
  '-C':
    'sub':      ['silence', 'unsilence', 'show-silenced']
    'dest':     'check'
    'help':     'Check name'
  '-e':
    'sub':      ['silence']
    'dest':     'expire'
    'help':     'Duration of silence entry in seconds'
    'required': False
    'default':  -1
  '-r':
    'sub':      ['silence']
    'dest':     'reason'
    'help':     'Reason for silencing'
    'required': False
    'default':  'silenced by himlarcli'
