nodes:
  access-01:
    compute_profile: small
    compute_resource: controller-03
  api-01:
    compute_profile: small
    compute_resource: controller-01
  api-02:
    compute_profile: small
    compute_resource: controller-02
  api-03:
    compute_profile: small
    compute_resource: controller-03
  api-internal-01:
    compute_profile: small
    compute_resource: controller-01
  api-internal-02:
    compute_profile: small
    compute_resource: controller-02
  api-internal-03:
    compute_profile: small
    compute_resource: controller-03
  builder-01:
    compute_profile: medium
    compute_resource: controller-03
    compute_attributes:
      volumes_attributes:
        '1':
          allocation:   '0G'
          pool_name:    'dirpool'
          capacity:     '120G'
          format_type:  'qcow2'
    host_parameters_attributes:
      - name:           'installdevice'
        value:          'vda'
  cephmds-01:
    compute_profile: medium
    compute_resource: controller-01
  cephmds-02:
    compute_profile: medium
    compute_resource: controller-02
  cephmds-03:
    compute_profile: medium
    compute_resource: controller-03
  cephmon-01:
    compute_profile: large
    compute_resource: controller-01
  cephmon-02:
    compute_profile: large
    compute_resource: controller-02
  cephmon-03:
    compute_profile: large
    compute_resource: controller-03
  compute-01:
    hostgroup: el8/legacy
    mac: 00:0a:f7:75:2f:80
    environment: ussuri
    # mac: f8:bc:12:3f:97:90
  compute-02:
    hostgroup: el8/legacy
    mac: f4:e9:d4:ad:38:e0
    # mac: 74:86:7a:d1:64:d6
  compute-03:
    hostgroup: el8/legacy
    mac: f4:e9:d4:ad:60:d0
    # mac: f8:bc:12:52:d8:48
  compute-04:
    hostgroup: el8/legacy
    mac: 00:0a:f7:19:75:80
  compute-05:
    hostgroup: el8/uefi
    mac: 00:0a:f7:97:80:c4
    environment: yoga
  console-01:
    compute_profile: medium
    compute_resource: controller-03
  controller-01:
    mac: 00:0a:f7:19:4c:c0
    hostgroup: 8
  controller-02:
    mac: f4:e9:d4:88:c9:c0
    hostgroup: 8
    # mac: f8:bc:12:40:44:30
  controller-03:
    mac: 00:0e:1e:8b:df:50
    hostgroup: 8
    # mac: f8:bc:12:52:d8:68
  controller-04:
    mac: 00:10:18:c3:d3:b0
    hostgroup: el8/uefi
  dashboard-01:
    compute_profile: large
    compute_resource: controller-02
  dashboard-mgmt-01:
    compute_profile: medium
    compute_resource: controller-03
  db-global-01:
    compute_profile: small
    compute_resource: controller-02
  db-regional-01:
    compute_profile: large
    compute_resource: controller-01
  dns-01:
    compute_profile: small
    compute_resource: controller-02
  identity-01:
    compute_profile: large
    compute_resource: controller-01
    hostgroup: el9/legacy
    environment: yoga_el9
  identity-02:
    compute_profile: large
    compute_resource: controller-02
    hostgroup: el9/legacy
    environment: yoga_el9
  identity-03:
    compute_profile: large
    compute_resource: controller-03
    hostgroup: el9/legacy
    environment: yoga_el9
  image-01:
    compute_profile: medium
    compute_resource: controller-01
  image-02:
    compute_profile: medium
    compute_resource: controller-02
  image-03:
    compute_profile: medium
    compute_resource: controller-03
    hostgroup: el9/legacy
    environment: yoga_el9
  logger-01:
    compute_profile: medium
    compute_resource: controller-03
    compute_attributes:
      volumes_attributes:
        '1':
          allocation:   '0G'
          pool_name:    'dirpool'
          capacity:     '100G'
          format_type:  'qcow2'
    host_parameters_attributes:
      - name:           'installdevice'
        value:          'vda'
  metric-01:
    compute_profile: xlarge
    environment: victoria
    compute_resource: controller-01
    compute_attributes:
      volumes_attributes:
        '1':
          allocation:   '0G'
          pool_name:    'dirpool'
          capacity:     '20G'
          format_type:  'qcow2'
    host_parameters_attributes:
      - name:           'installdevice'
        value:          'vda'
  monitor-01:
    compute_profile: medium
    compute_resource: controller-01
  mq-01:
    compute_profile: medium
    compute_resource: controller-01
  nat-01:
    compute_profile: small
    compute_resource: controller-03
  network-01:
    compute_profile: large
    compute_resource: controller-01
  network-02:
    compute_profile: large
    compute_resource: controller-02
  network-03:
    compute_profile: large
    compute_resource: controller-03
  novactrl-01:
    compute_profile: large
    compute_resource: controller-01
  novactrl-02:
    compute_profile: large
    compute_resource: controller-02
  ns-01:
    compute_profile: small
    compute_resource: controller-01
  proxy-01:
    compute_profile: small
    compute_resource: controller-03
    hostgroup: el9/legacy
    environment: yoga_el9
    # compute_attributes:
    #   volumes_attributes:
    #     '1':
    #       allocation:   '0G'
    #       pool_name:    'dirpool'
    #       capacity:     '50G'
    #       format_type:  'raw'
    # host_parameters_attributes:
    #   - name:           'installdevice'
    #     value:          'vda'
  proxy-02:
    compute_profile: small
    compute_resource: controller-03
    compute_attributes:
      volumes_attributes:
        '1':
          allocation:   '0G'
          pool_name:    'dirpool'
          capacity:     '50G'
          format_type:  'qcow2'
    host_parameters_attributes:
      - name:           'installdevice'
        value:          'vda'
  report-01:
    compute_profile: small
    compute_resource: controller-03
  resolver-01:
    compute_profile: small
    compute_resource: controller-02
  resolver-02:
    compute_profile: small
    compute_resource: controller-03
  sensugo-01:
    compute_profile: medium
    compute_resource: controller-01
    hostgroup: el9/legacy
    environment: monitor
  sensugo-02:
    compute_profile: small
    compute_resource: controller-02
    hostgroup: el9/legacy
    environment: monitor
  sensugo-03:
    compute_profile: small
    compute_resource: controller-03
    hostgroup: el9/legacy
    environment: monitor
  status-01:
    compute_profile: medium
    compute_resource: controller-03
  storage-01:
    hostgroup: 4
    mac: 18:66:da:51:60:64
  storage-02:
    hostgroup: 4
    mac: 18:66:da:51:62:1f
  storage-03:
    hostgroup: 4
    mac: 18:66:da:51:70:a7
  storage-04:
    hostgroup: 4
    mac: 18:66:da:51:6e:65
  storage-05:
    hostgroup: 4
    mac: b0:83:fe:e8:3a:31
  telemetry-01:
    compute_profile: xlarge
    compute_resource: controller-02
    hostgroup: el9/legacy
    environment: yoga_el9
  tsdb-01:
    compute_profile: small
    compute_resource: controller-03
    hostgroup: el9/legacy
    environment: monitor
    compute_attributes:
      volumes_attributes:
        '1':
          allocation:   '0G'
          pool_name:    'dirpool'
          capacity:     '50G'
          format_type:  'qcow2'
    host_parameters_attributes:
      - name:           'installdevice'
        value:          'vda'
  volume-01:
    compute_profile: large
    compute_resource: controller-01
    compute_attributes:
      volumes_attributes:
        '1':
          allocation:   '0G'
          pool_name:    'dirpool'
          capacity:     '20G'
          format_type:  'qcow2'
  volume-02:
    compute_profile: large
    compute_resource: controller-02
    compute_attributes:
      volumes_attributes:
        '1':
          allocation:   '0G'
          pool_name:    'dirpool'
          capacity:     '20G'
          format_type:  'qcow2'
  workflow-01:
    compute_profile: small
    compute_resource: controller-03
  vendorapi-01:
    compute_profile: small
    compute_resource: controller-03
